# Generated by Django 3.0.5 on 2020-11-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='heading',
            field=models.CharField(max_length=60),
        ),
    ]
