# Generated by Django 3.0.5 on 2020-11-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streetfood', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='places',
            new_name='streetfood',
        ),
    ]
