# Generated by Django 3.0.5 on 2020-11-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutcity', '0002_auto_20201114_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcity',
            name='image',
            field=models.ImageField(upload_to='city/images'),
        ),
    ]
